[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/_next/static/:splat"
  status = 200
  force = false
  condition = { path = { matches = "^/_next/static/.*" } }

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
